version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/social-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # aby hot-reload działał w Dockerze
    networks:
      - mynetwork

  identityapi:
    build:
      context: ./IdentityAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IdentityDb;User=sa;Password=Your_password123;
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork: