version: "3.8"

services:
  identityapi:
    build:
      context: ./IdentityAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IdentityDb;User=sa;Password=Your_password123;
    networks:
      - mynetwork

  postapi:
    build:
      context: ./PostAPI
      dockerfile: Dockerfile
    container_name: postapi
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver
    networks:
      - mynetwork

  commentapi:
    build:
      context: ./CommentAPI2
      dockerfile: Dockerfile
    container_name: commentapi
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver
    networks:
      - mynetwork

  # frontend:
  #   build:
  #     context: ./FrontendMVC
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "5003:80"
  #   networks:
  #     - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    networks:
      - mynetwork

networks:
  mynetwork:
